# Generic RAPP Platform Travis Continuous Integration Configuration File
# Author: Manos Tsardoulias, Aris Thallas
# Contact: etsardou@gmail.com, aris.thallas@{iti.gr, gmail.com}
sudo: required
dist: trusty
language: generic
compiler:
  - gcc
env:
  global:
    - secure: jctNCksS3N66zVjML58EHB9FqRi6HaGV4o32Y+84epKt4vP0RMxuf5MrWAUDvZVAs9ojstG9LHni39tlCvmAulEGWNbeq6J8aVe3H+BaazXsSmfXZh+8IXqt1nc9T40Tw0DmsMTcExZwdjL5om1mLlaHGsnGKGUzjamEYXKORKM=
before_install: # Use this to prepare the system to install prerequisites or dependencies
  # Define some config vars
  - export ROS_DISTRO=indigo
  - export CI_SOURCE_PATH=$(pwd)
  - export REPOSITORY_NAME=${PWD##*/}
  - export RAPP_WS=~/rapp_platform/rapp-platform-catkin-ws
  - export RAPP_PL=$RAPP_WS/src/rapp-platform
  - echo "Testing branch $TRAVIS_BRANCH of $REPOSITORY_NAME"
  # Perform system updates and install needed packages
  - echo "Installing needed libraries"
  - sudo apt-get update
  - sudo apt-get install -qq -y git mercurial screen &> /dev/null
install: true # Use this to install any prerequisites or dependencies necessary to run your build
script: # All commands must exit with code 0 on success. Anything else is considered failure.
  # First test the install scripts
  - echo "Performing clean installation of rapp-platform"
  - cd rapp_scripts/setup
  #- source /opt/ros/$ROS_DISTRO/setup.bash
  - bash clean_install.sh travis
  - source ~/.bashrc
  - sudo ldconfig
  - echo "RAPP Platform installed. Executing unit and functional tests"
  # Run unit and functional tests
  - cd $RAPP_WS
  - catkin_make run_tests -j1
  - catkin_test_results
  - catkin_make test -j1
  # Run integration tests
  - echo "Initiating integration tests"
  - screen -d -m $RAPP_PL/rapp_scripts/deploy/deploy_rapp_ros.sh
  - screen -d -m $RAPP_PL/rapp_scripts/deploy/deploy_web_services.sh
  - sleep 20
  - echo "Executing normal integration tests"
  - rosrun rapp_testing_tools rapp_run_test.py
after_success:
  # Create documentation on conditions
  - test $TRAVIS_PULL_REQUEST = false \
    && test $TRAVIS_BRANCH = "master" \ 
    && echo "Creating online documentation" \
    && sudo apt-get install -qq -y doxygen texlive-full &> /dev/null \
    && cd $RAPP_PL/rapp_scripts/documentation \
    && bash update_rapp-project.github.io.sh \
    && echo "Documentation created and updated online"
